# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "703b8999c26dd975904bbe546f93a7a6"
name = "review-checkout-app"
handle = "review-checkout-app-1"
application_url = "https://liverpool-caps-murray-rs.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "coronachen.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://liverpool-caps-murray-rs.trycloudflare.com/auth/callback",
  "https://liverpool-caps-murray-rs.trycloudflare.com/auth/shopify/callback",
  "https://liverpool-caps-murray-rs.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
